apiVersion: apps/v1
kind: Deployment
metadata:
  name: jayashrim-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jayashrim-springboot
  template:
    metadata:
      labels:
        app: jayashrim-springboot
    spec:
      containers:
        - name: springboot
          image: jayashrimahale22/k8s-dockerpoc-demo:k8s-dockerpoc-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jayashrim-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jayashrim-springboot
